### ISSUE TITLE
Funções de pacotes desconhecidos em data-proc-nc.R

### ISSUE THREAD

**Issue by GuilhermeTorma** [lhmet-mentor/down-nmme#2]
Função GlanceNetCDF() em .n_dim_nc (número de membros) e a função export_bin_file() em out_file @lhmet

**Comment by lhmet** [comment]
Já dei push 
metR::GlanceNETCDF()

**Comment by lhmet** [comment]
Fechando esta questão.

**Comment by lhmet** [comment]
Confira se tem todos pacotes citados no README.
Fechando a issue.
