### ISSUE TITLE
Função filter_lead_time

### ISSUE THREAD

**Issue by GuilhermeTorma** [lhmet-mentor/down-nmme#3]
A função filter_lead_time do scripit data-proc-nc.R

**Comment by GuilhermeTorma** [comment]
A função não está retornando algo após aplicar prec_year_mod[, model_name()] @lhmet

**Comment by lhmet** [comment]
@GuilhermeTorma fiz uma atualização nos arquivos, faça um pull antes de implementar mais mudanças

**Comment by lhmet** [comment]
Funcao removida
