### ISSUE TITLE
Inclusão de modelos climáticos (que disponibilizam previsão em tempo real)

### ISSUE THREAD

**Issue by lhmet** [lhmet-mentor/down-nmme#5]
@GuilhermeTorma veja se consegue incluir:

1. http://iridl.ldeo.columbia.edu/SOURCES/.Models/.NMME/.NASA-GMAO-062012/.MONTHLY/.prec/

2. https://iridl.ldeo.columbia.edu/SOURCES/.Models/.NMME/.CanSIPS-IC3/.GEM5-NEMO/.FORECAST/.MONTHLY/.prec/

3. http://iridl.ldeo.columbia.edu/SOURCES/.Models/.NMME/.COLA-RSMAS-CCSM4/.MONTHLY/.prec

**Comment by GuilhermeTorma** [comment]
@lhmet 
Incluído e download realizado.

**Comment by lhmet** [comment]
@GuilhermeTorma quando posso pegar os dados contigo ?

**Comment by GuilhermeTorma** [comment]
@lhmet, depois das 15:30 de hoje.

**Comment by lhmet** [comment]
Feito!
