### ISSUE TITLE
Realizando download de arquivos já existentes

### ISSUE THREAD

**Issue by GuilhermeTorma** [lhmet-mentor/down-nmme#6]
O programa não está retornando arquivos existentes e está realizando download dos mesmos. Por enquanto, não consegui encontrar o problema.
@lhmet

**Comment by GuilhermeTorma** [comment]
Entendi, o porquê disso está acontecendo. Detalhe que passou batido por mim.

**Comment by lhmet** [comment]
Especifique o detalhe por gentileza para ecerrarmos esta issue com informação necessária.

**Comment by GuilhermeTorma** [comment]
Correto. O overwrite está como TRUE em baixados (down-hindcasts-nmme.R), assim, o arquivo será baixado mesmo que ele já exista. Uma pequena alteração de TRUE para FALSE resolve isso.
